/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.app.github.actions;

public class App {
    public String getGreeting() {
        return "GRADLE JAVA APP GITHUB ACTIONS EXAMPLE";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
